### PR TITLE
Fixes #32443 - Add support for md5 for ALLOWED_CONTENT_CHECKSUM

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
@wbclark this needs to be in whatever puppet-fpc release we'll have for Katello 4.1 RC1

**Review by ekohl — COMMENTED** [review]
Is this `Refs #32338` since it corrects https://github.com/theforeman/puppet-foreman_proxy_content/commit/85bcb81d7313c95114544a1b1967adb70c7ffa31?

**Comment by jlsherrill** [comment]
> Is this `Refs #32338` since it corrects [85bcb81](https://github.com/theforeman/puppet-foreman_proxy_content/commit/85bcb81d7313c95114544a1b1967adb70c7ffa31)?

this seemed kinda like a bug ontop of that one, but i can do that if preferred

**Comment by ekohl** [comment]
I'm mostly concerned about proper tracking. Its own issue would also be fine.

**Comment by jlsherrill** [comment]
ugg i filed an issue and then forgot to link  --me

**Review by wbclark — APPROVED** [review]
LGTM. Thanks @jlsherrill !

**Pull request merged**
