### PR TITLE
Fixes #29278: Use default CA for crane SSL chain

### PR DESCRIPTION
**Pull request by ekohl**
(cherry picked from commit 85f85fc1b12c693101156559708c5a855113ff47)

### CODE REVIEW

**Comment by evgeni** [comment]
`Resource type not found: Redis::RedisUrl` :(

**Comment by evgeni** [comment]
(ACK on the change, tho, just make Travis happy please :) )

**Comment by ehelms** [comment]
@ekohl could you tackle this for me please

**Comment by philipp1992** [comment]
hi,

we are facing the same issue with custom ssl certs and katello 3.15 + foreman 2.0.
Ive tried to apply that patch to the manifest/init.pp file, but when i re-run the foreman-installer, i get an error saying, that there is no cache file for init.pp and no puppet module parser.

Any hints on how to apply this fix to a foreman 2.0 installation without upgrading to the nightly build?

**Pull request merged**
