### PR TITLE
Added passthrough pulp mode

### PR DESCRIPTION
**Pull request by sbernhard**
See https://github.com/theforeman/puppet-pulp/pull/372 for more details

### CODE REVIEW

**Comment by ehelms** [comment]
I sorta asked this on puppet-pulp, but maybe it makes more sense in this context. What benefit does the pass through provide if a full blown Pulp is deployed?

**Comment by sbernhard** [comment]
I guess, the failure occurs becaue https://github.com/theforeman/puppet-pulp/pull/372 is not merged?

**Comment by sbernhard** [comment]
See last comment in https://github.com/theforeman/puppet-pulp/pull/372

**Comment by ehelms** [comment]
The master branch now reflects a world where Katello does not rely on Pulp 2. I am therefore closing this issue as it is no longer applicable to todays deployment model.

**Pull request closed without merging**
