### PR TITLE
Fixes #37620 - Use the correct docroot in the reverse proxy setup

### PR DESCRIPTION
**Pull request by ekohl**
This is a code dump of what I was working on.

### CODE REVIEW

**Comment by ehelms** [comment]
Do you think there is any way to add an acceptance test for either `/cgi-bin` or the Apache multiviews directory listing?

**Comment by ekohl** [comment]
Looking at what it now serves is an a directory listing without entries:
```console
$ curl https://localhost -k
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
  <table>
   <tr><th valign="top"><img src="/icons/blank.gif" alt="[ICO]"></th><th><a href="?C=N;O=D">Name</a></th><th><a href="?C=M;O=A">Last modified</a></th><th><a href="?C=S;O=A">Size</a></th><th><a href="?C=D;O=A">Description</a></th></tr>
   <tr><th colspan="5"><hr></th></tr>
   <tr><th colspan="5"><hr></th></tr>
</table>
</body></html>
```

It's slightly misleading that it doesn't list `/pub` even though it will be served. I'm tempted to always add `/var/lib/pulp/pulpcore_static/index.html` which would also avoid stupid scanners thinking multiviews is still a thing. Or should we add some placeholder there to inform the user what it's for?

**Comment by ehelms** [comment]
> It's slightly misleading that it doesn't list `/pub` even though it will be served. I'm tempted to always add `/var/lib/pulp/pulpcore_static/index.html` which would also avoid stupid scanners thinking multiviews is still a thing. Or should we add some placeholder there to inform the user what it's for?

I'm OK with a blank file being added. Would be nice to document why we have it - which could be through a comment or by stating that on the file itself.

**Comment by ekohl** [comment]
Current version instead disables indexes and now it shows a HTTP 403 page. I didn't include a test because we don't have the [curl_command](https://github.com/theforeman/puppet-pulpcore/blob/master/spec/support/acceptance/curl_command.rb) helper here. @evgeni mentioned he'd like it some other place as well so I intend to move it to [voxpupuli-acceptance](https://github.com/voxpupuli/voxpupuli-acceptance) but I'd prefer to not block this PR on it.

**Review by ehelms — APPROVED** [review]
I got a 403 on `/` and all other endpoints I should browse are visible.

**Pull request merged**
