### PR TITLE
Fixes #32338 - expose pulpcore allowed_content_checksums

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
requires https://github.com/theforeman/puppet-pulpcore/pull/183

**Review by wbclark — COMMENTED** [review]
This will require a puppet-pulpcore release with https://github.com/theforeman/puppet-pulpcore/pull/183

That release should be version 3.3.0

Therefore we should go ahead and increase the minimum version for puppet-pulpcore to 3.3.0

**Comment by wbclark** [comment]
Same feedback applies re: commit message as on the other PR. If there is a Redmine for this issue, please attach it. Thanks!

**Comment by ehelms** [comment]
You can now update https://github.com/theforeman/puppet-foreman_proxy_content/blob/master/metadata.json#L37 to a minimum of `3.3.0`

**Comment by jlsherrill** [comment]
this is now green

**Review by ehelms — APPROVED** [review]

**Pull request merged**
