### PR TITLE
Add support for Pulp Yum repository metadata signatures

### PR DESCRIPTION
**Pull request by PaulSD**
See https://github.com/theforeman/puppet-certs/pull/188

This is dependent on the following PRs and will fail unit tests until they are merged:
https://github.com/theforeman/puppet-certs/pull/188
https://github.com/theforeman/puppet-pulp/pull/321
https://github.com/theforeman/puppet-pulp/pull/322

### CODE REVIEW

**Comment by ehelms** [comment]
@PaulSD First, I want to apologize for the long back and forth with this contributed feature. I have let other things get in my way and not give it the attention it deserved. Pulp 3 is well on it's way into the ecosystem with Katello's current RC running with Pulp 3 for files and container content. With this in mind, I would like to prefer building this within the Pulp 3 ecosystem since this change won't be long lived within the current release targets. Looks like if my searching is correct this is being tracked (and already implemented) here https://pulp.plan.io/issues/4812

**Comment by PaulSD** [comment]
@ehelms The overall "feature" here consists of three components:
1. Server-side support in Pulp for generating repository metadata signatures
2. Client-side support in Candlepin / subscription-manager for configuring keys and enabling signature checking on the client
3. Updates to satellite-installer to glue everything together and expose the underlying feature to end users

**"1"** has been fully implemented and released in Pulp 2.17 / Satellite 6.5
**"2"** has been fully implemented and released in subscription-manager 1.21.1
Since the release of Satellite 6.5, it has been possible to manually configure Pulp and each client to enable repository metadata signature generation/checking after running satellite-installer: https://bugzilla.redhat.com/show_bug.cgi?id=1410638#c54

This PR (and the others referenced at the top of this PR) are intended to implement **"3"** and eliminate the manual configuration.

It looks like https://pulp.plan.io/issues/4812 reimplements **"1"** for Pulp 3.  However, that doesn't eliminate the need for these PRs.  When satellite-installer is updated to install Pulp 3 instead of Pulp 2, https://github.com/theforeman/puppet-pulp/pull/321 (already merged) and https://github.com/theforeman/puppet-pulp/pull/322 (not yet merged) will need to be reimplemented to work with Pulp 3, but otherwise I think the remaining PRs will all remain as-is.

**Comment by PaulSD** [comment]
For reference, the full list of remaining PRs for satellite-installer:
https://github.com/theforeman/puppet-pulp/pull/322
https://github.com/Katello/katello-certs-tools/pull/3
https://github.com/theforeman/puppet-certs/pull/188
https://github.com/theforeman/puppet-foreman_proxy_content/pull/167
https://github.com/theforeman/puppet-katello/pull/245
https://github.com/theforeman/puppet-katello_devel/pull/160

**Comment by ehelms** [comment]
The installer itself is not being replaced but there are discussions / work in progress that will replace (drop support for) some functionality:

 * https://github.com/theforeman/puppet-pulpcore -- where all Pulp 3 logic for installer is handled
 * https://github.com/theforeman/puppet-foreman_proxy_content/blob/master/manifests/init.pp#L324 -- configuration logic for Pulp 3 (this may move)
 * Certificate handling redesign (https://community.theforeman.org/t/rfc-redesign-certificate-handling-within-foreman-deployments/17933)

**Comment by PaulSD** [comment]
Ok.
So it looks like theforeman/puppet-pulp#321 and theforeman/puppet-pulp#322 will need to be reimplemented in puppet-pulpcore ... but first, it looks like puppet-pulpcore needs to be extended to also stand up a signing service for Pulp 3 to use?
Some minor updates will be needed to this PR to pass the parameters through to puppet-pulpcore instead of puppet-pulp.
The certificate handling redesign work should include support for generating the necessary GPG key for this (currently implemented in theforeman/puppet-certs#188 ).
Katello/katello-certs-tools#3 may or may not be needed depending on whether the certificate handling redesign also replaces the client RPM generation code.
And theforeman/puppet-katello#245 and theforeman/puppet-katello_devel#160 should remain as-is (these PRs just expose the parameters).

**Comment by ehelms** [comment]
The master branch now reflects a world where Katello does not rely on Pulp 2. I am therefore closing this issue as it is no longer applicable to todays deployment model. 

I apologize for never having to around to implementing this. I sincerely hope that with Pulp 3 we are able to resolve this in a simple and usable way for users.

**Pull request closed without merging**
