### PR TITLE
Make dispatch router standalone classes

### PR DESCRIPTION
**Pull request by ekohl**
This makes it clearer how it's used and allows standalone inclusion.

### CODE REVIEW

**Comment by ekohl** [comment]
My main question is whether the `connector` and `hub` should have parameters of `dispatch_router` so they're complete classes.

**Comment by ehelms** [comment]
Can you expand on the question you posed? I think this is a bit of puppetese I don't understand.

**Comment by ekohl** [comment]
The current intended use is (as a connector):
```puppet
class { 'foreman_proxy_content::dispatch_router': 
  agent_addr => $addr,
  # ...
}
class { 'foreman_proxy_content::dispatch_router::connector':
  # connector options
}
```

I'm wondering if it should only call connector and connector should pass options to `foreman_proxy_content::dispatch_router`.

At this point I think I'd start with the current implementation but would be open to other suggestions.

**Comment by ehelms** [comment]
If the base dispatch_router class is more of a common setup for both connector and hub, I would just have users call connector and hide the router part. If ther eare enough configurables on the dispatch_router itself, then it makes sense to me to keep them separate.

**Comment by ekohl** [comment]
The `connector` is what we deploy on a content proxy and the `hub` is what we deploy on a katello scenario. It would duplicate parameters but the calling code is more straight forward.

**Comment by ehelms** [comment]
Sounds good to me

**Pull request merged**
